/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ParceiroRouteImport } from './routes/parceiro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LinkRouteImport } from './routes/link'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ParceiroIndexRouteImport } from './routes/parceiro.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ParceiroPromotoresRouteImport } from './routes/parceiro.promotores'
import { Route as ParceiroPagamentosRouteImport } from './routes/parceiro.pagamentos'
import { Route as ParceiroDepositosRouteImport } from './routes/parceiro.depositos'
import { Route as AdminPayoutsRouteImport } from './routes/admin/payouts'
import { Route as AdminPartnersRouteImport } from './routes/admin/partners'
import { Route as AuthenticatedReceberRouteImport } from './routes/_authenticated/receber'
import { Route as AuthenticatedExtratoRouteImport } from './routes/_authenticated/extrato'
import { Route as ParceiroPromotoresIndexRouteImport } from './routes/parceiro.promotores.index'
import { Route as AdminPromotersIndexRouteImport } from './routes/admin/promoters.index'
import { Route as AdminCommissionsIndexRouteImport } from './routes/admin/commissions.index'
import { Route as ParceiroPromotoresIdRouteImport } from './routes/parceiro.promotores.$id'
import { Route as AdminPromotersIdRouteImport } from './routes/admin/promoters.$id'
import { Route as AdminCommissionsRatesRouteImport } from './routes/admin/commissions.rates'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceiroRoute = ParceiroRouteImport.update({
  id: '/parceiro',
  path: '/parceiro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkRoute = LinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceiroIndexRoute = ParceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParceiroRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ParceiroPromotoresRoute = ParceiroPromotoresRouteImport.update({
  id: '/promotores',
  path: '/promotores',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroPagamentosRoute = ParceiroPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroDepositosRoute = ParceiroDepositosRouteImport.update({
  id: '/depositos',
  path: '/depositos',
  getParentRoute: () => ParceiroRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedReceberRoute = AuthenticatedReceberRouteImport.update({
  id: '/receber',
  path: '/receber',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExtratoRoute = AuthenticatedExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ParceiroPromotoresIndexRoute = ParceiroPromotoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParceiroPromotoresRoute,
} as any)
const AdminPromotersIndexRoute = AdminPromotersIndexRouteImport.update({
  id: '/promoters/',
  path: '/promoters/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommissionsIndexRoute = AdminCommissionsIndexRouteImport.update({
  id: '/commissions/',
  path: '/commissions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ParceiroPromotoresIdRoute = ParceiroPromotoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ParceiroPromotoresRoute,
} as any)
const AdminPromotersIdRoute = AdminPromotersIdRouteImport.update({
  id: '/promoters/$id',
  path: '/promoters/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommissionsRatesRoute = AdminCommissionsRatesRouteImport.update({
  id: '/commissions/rates',
  path: '/commissions/rates',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/link': typeof LinkRoute
  '/onboarding': typeof OnboardingRoute
  '/parceiro': typeof ParceiroRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/extrato': typeof AuthenticatedExtratoRoute
  '/receber': typeof AuthenticatedReceberRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/parceiro/depositos': typeof ParceiroDepositosRoute
  '/parceiro/pagamentos': typeof ParceiroPagamentosRoute
  '/parceiro/promotores': typeof ParceiroPromotoresRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/parceiro/': typeof ParceiroIndexRoute
  '/admin/commissions/rates': typeof AdminCommissionsRatesRoute
  '/admin/promoters/$id': typeof AdminPromotersIdRoute
  '/parceiro/promotores/$id': typeof ParceiroPromotoresIdRoute
  '/admin/commissions/': typeof AdminCommissionsIndexRoute
  '/admin/promoters/': typeof AdminPromotersIndexRoute
  '/parceiro/promotores/': typeof ParceiroPromotoresIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/link': typeof LinkRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/extrato': typeof AuthenticatedExtratoRoute
  '/receber': typeof AuthenticatedReceberRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/parceiro/depositos': typeof ParceiroDepositosRoute
  '/parceiro/pagamentos': typeof ParceiroPagamentosRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminIndexRoute
  '/parceiro': typeof ParceiroIndexRoute
  '/admin/commissions/rates': typeof AdminCommissionsRatesRoute
  '/admin/promoters/$id': typeof AdminPromotersIdRoute
  '/parceiro/promotores/$id': typeof ParceiroPromotoresIdRoute
  '/admin/commissions': typeof AdminCommissionsIndexRoute
  '/admin/promoters': typeof AdminPromotersIndexRoute
  '/parceiro/promotores': typeof ParceiroPromotoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/link': typeof LinkRoute
  '/onboarding': typeof OnboardingRoute
  '/parceiro': typeof ParceiroRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/extrato': typeof AuthenticatedExtratoRoute
  '/_authenticated/receber': typeof AuthenticatedReceberRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/parceiro/depositos': typeof ParceiroDepositosRoute
  '/parceiro/pagamentos': typeof ParceiroPagamentosRoute
  '/parceiro/promotores': typeof ParceiroPromotoresRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/parceiro/': typeof ParceiroIndexRoute
  '/admin/commissions/rates': typeof AdminCommissionsRatesRoute
  '/admin/promoters/$id': typeof AdminPromotersIdRoute
  '/parceiro/promotores/$id': typeof ParceiroPromotoresIdRoute
  '/admin/commissions/': typeof AdminCommissionsIndexRoute
  '/admin/promoters/': typeof AdminPromotersIndexRoute
  '/parceiro/promotores/': typeof ParceiroPromotoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/link'
    | '/onboarding'
    | '/parceiro'
    | '/sitemap.xml'
    | '/extrato'
    | '/receber'
    | '/admin/partners'
    | '/admin/payouts'
    | '/parceiro/depositos'
    | '/parceiro/pagamentos'
    | '/parceiro/promotores'
    | '/admin/'
    | '/parceiro/'
    | '/admin/commissions/rates'
    | '/admin/promoters/$id'
    | '/parceiro/promotores/$id'
    | '/admin/commissions/'
    | '/admin/promoters/'
    | '/parceiro/promotores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/link'
    | '/onboarding'
    | '/sitemap.xml'
    | '/extrato'
    | '/receber'
    | '/admin/partners'
    | '/admin/payouts'
    | '/parceiro/depositos'
    | '/parceiro/pagamentos'
    | '/'
    | '/admin'
    | '/parceiro'
    | '/admin/commissions/rates'
    | '/admin/promoters/$id'
    | '/parceiro/promotores/$id'
    | '/admin/commissions'
    | '/admin/promoters'
    | '/parceiro/promotores'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/link'
    | '/onboarding'
    | '/parceiro'
    | '/sitemap.xml'
    | '/_authenticated/extrato'
    | '/_authenticated/receber'
    | '/admin/partners'
    | '/admin/payouts'
    | '/parceiro/depositos'
    | '/parceiro/pagamentos'
    | '/parceiro/promotores'
    | '/_authenticated/'
    | '/admin/'
    | '/parceiro/'
    | '/admin/commissions/rates'
    | '/admin/promoters/$id'
    | '/parceiro/promotores/$id'
    | '/admin/commissions/'
    | '/admin/promoters/'
    | '/parceiro/promotores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LinkRoute: typeof LinkRoute
  OnboardingRoute: typeof OnboardingRoute
  ParceiroRoute: typeof ParceiroRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiro': {
      id: '/parceiro'
      path: '/parceiro'
      fullPath: '/parceiro'
      preLoaderRoute: typeof ParceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link': {
      id: '/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiro/': {
      id: '/parceiro/'
      path: '/'
      fullPath: '/parceiro/'
      preLoaderRoute: typeof ParceiroIndexRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/parceiro/promotores': {
      id: '/parceiro/promotores'
      path: '/promotores'
      fullPath: '/parceiro/promotores'
      preLoaderRoute: typeof ParceiroPromotoresRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/pagamentos': {
      id: '/parceiro/pagamentos'
      path: '/pagamentos'
      fullPath: '/parceiro/pagamentos'
      preLoaderRoute: typeof ParceiroPagamentosRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/depositos': {
      id: '/parceiro/depositos'
      path: '/depositos'
      fullPath: '/parceiro/depositos'
      preLoaderRoute: typeof ParceiroDepositosRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/receber': {
      id: '/_authenticated/receber'
      path: '/receber'
      fullPath: '/receber'
      preLoaderRoute: typeof AuthenticatedReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extrato': {
      id: '/_authenticated/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof AuthenticatedExtratoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/parceiro/promotores/': {
      id: '/parceiro/promotores/'
      path: '/'
      fullPath: '/parceiro/promotores/'
      preLoaderRoute: typeof ParceiroPromotoresIndexRouteImport
      parentRoute: typeof ParceiroPromotoresRoute
    }
    '/admin/promoters/': {
      id: '/admin/promoters/'
      path: '/promoters'
      fullPath: '/admin/promoters/'
      preLoaderRoute: typeof AdminPromotersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/commissions/': {
      id: '/admin/commissions/'
      path: '/commissions'
      fullPath: '/admin/commissions/'
      preLoaderRoute: typeof AdminCommissionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/parceiro/promotores/$id': {
      id: '/parceiro/promotores/$id'
      path: '/$id'
      fullPath: '/parceiro/promotores/$id'
      preLoaderRoute: typeof ParceiroPromotoresIdRouteImport
      parentRoute: typeof ParceiroPromotoresRoute
    }
    '/admin/promoters/$id': {
      id: '/admin/promoters/$id'
      path: '/promoters/$id'
      fullPath: '/admin/promoters/$id'
      preLoaderRoute: typeof AdminPromotersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/commissions/rates': {
      id: '/admin/commissions/rates'
      path: '/commissions/rates'
      fullPath: '/admin/commissions/rates'
      preLoaderRoute: typeof AdminCommissionsRatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedExtratoRoute: typeof AuthenticatedExtratoRoute
  AuthenticatedReceberRoute: typeof AuthenticatedReceberRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedExtratoRoute: AuthenticatedExtratoRoute,
  AuthenticatedReceberRoute: AuthenticatedReceberRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCommissionsRatesRoute: typeof AdminCommissionsRatesRoute
  AdminPromotersIdRoute: typeof AdminPromotersIdRoute
  AdminCommissionsIndexRoute: typeof AdminCommissionsIndexRoute
  AdminPromotersIndexRoute: typeof AdminPromotersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCommissionsRatesRoute: AdminCommissionsRatesRoute,
  AdminPromotersIdRoute: AdminPromotersIdRoute,
  AdminCommissionsIndexRoute: AdminCommissionsIndexRoute,
  AdminPromotersIndexRoute: AdminPromotersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ParceiroPromotoresRouteChildren {
  ParceiroPromotoresIdRoute: typeof ParceiroPromotoresIdRoute
  ParceiroPromotoresIndexRoute: typeof ParceiroPromotoresIndexRoute
}

const ParceiroPromotoresRouteChildren: ParceiroPromotoresRouteChildren = {
  ParceiroPromotoresIdRoute: ParceiroPromotoresIdRoute,
  ParceiroPromotoresIndexRoute: ParceiroPromotoresIndexRoute,
}

const ParceiroPromotoresRouteWithChildren =
  ParceiroPromotoresRoute._addFileChildren(ParceiroPromotoresRouteChildren)

interface ParceiroRouteChildren {
  ParceiroDepositosRoute: typeof ParceiroDepositosRoute
  ParceiroPagamentosRoute: typeof ParceiroPagamentosRoute
  ParceiroPromotoresRoute: typeof ParceiroPromotoresRouteWithChildren
  ParceiroIndexRoute: typeof ParceiroIndexRoute
}

const ParceiroRouteChildren: ParceiroRouteChildren = {
  ParceiroDepositosRoute: ParceiroDepositosRoute,
  ParceiroPagamentosRoute: ParceiroPagamentosRoute,
  ParceiroPromotoresRoute: ParceiroPromotoresRouteWithChildren,
  ParceiroIndexRoute: ParceiroIndexRoute,
}

const ParceiroRouteWithChildren = ParceiroRoute._addFileChildren(
  ParceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LinkRoute: LinkRoute,
  OnboardingRoute: OnboardingRoute,
  ParceiroRoute: ParceiroRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
