/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReceberRouteImport } from './routes/receber'
import { Route as ParceiroRouteImport } from './routes/parceiro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LinkRouteImport } from './routes/link'
import { Route as ExtratoRouteImport } from './routes/extrato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParceiroIndexRouteImport } from './routes/parceiro.index'
import { Route as ParceiroPromotoresRouteImport } from './routes/parceiro.promotores'
import { Route as ParceiroPagamentosRouteImport } from './routes/parceiro.pagamentos'
import { Route as ParceiroDepositosRouteImport } from './routes/parceiro.depositos'
import { Route as ParceiroPromotoresIdRouteImport } from './routes/parceiro.promotores.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceberRoute = ReceberRouteImport.update({
  id: '/receber',
  path: '/receber',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceiroRoute = ParceiroRouteImport.update({
  id: '/parceiro',
  path: '/parceiro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkRoute = LinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratoRoute = ExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceiroIndexRoute = ParceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroPromotoresRoute = ParceiroPromotoresRouteImport.update({
  id: '/promotores',
  path: '/promotores',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroPagamentosRoute = ParceiroPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroDepositosRoute = ParceiroDepositosRouteImport.update({
  id: '/depositos',
  path: '/depositos',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroPromotoresIdRoute = ParceiroPromotoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ParceiroPromotoresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extrato': typeof ExtratoRoute
  '/link': typeof LinkRoute
  '/onboarding': typeof OnboardingRoute
  '/parceiro': typeof ParceiroRouteWithChildren
  '/receber': typeof ReceberRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parceiro/depositos': typeof ParceiroDepositosRoute
  '/parceiro/pagamentos': typeof ParceiroPagamentosRoute
  '/parceiro/promotores': typeof ParceiroPromotoresRouteWithChildren
  '/parceiro/': typeof ParceiroIndexRoute
  '/parceiro/promotores/$id': typeof ParceiroPromotoresIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extrato': typeof ExtratoRoute
  '/link': typeof LinkRoute
  '/onboarding': typeof OnboardingRoute
  '/receber': typeof ReceberRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parceiro/depositos': typeof ParceiroDepositosRoute
  '/parceiro/pagamentos': typeof ParceiroPagamentosRoute
  '/parceiro/promotores': typeof ParceiroPromotoresRouteWithChildren
  '/parceiro': typeof ParceiroIndexRoute
  '/parceiro/promotores/$id': typeof ParceiroPromotoresIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extrato': typeof ExtratoRoute
  '/link': typeof LinkRoute
  '/onboarding': typeof OnboardingRoute
  '/parceiro': typeof ParceiroRouteWithChildren
  '/receber': typeof ReceberRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parceiro/depositos': typeof ParceiroDepositosRoute
  '/parceiro/pagamentos': typeof ParceiroPagamentosRoute
  '/parceiro/promotores': typeof ParceiroPromotoresRouteWithChildren
  '/parceiro/': typeof ParceiroIndexRoute
  '/parceiro/promotores/$id': typeof ParceiroPromotoresIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extrato'
    | '/link'
    | '/onboarding'
    | '/parceiro'
    | '/receber'
    | '/sitemap.xml'
    | '/parceiro/depositos'
    | '/parceiro/pagamentos'
    | '/parceiro/promotores'
    | '/parceiro/'
    | '/parceiro/promotores/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extrato'
    | '/link'
    | '/onboarding'
    | '/receber'
    | '/sitemap.xml'
    | '/parceiro/depositos'
    | '/parceiro/pagamentos'
    | '/parceiro/promotores'
    | '/parceiro'
    | '/parceiro/promotores/$id'
  id:
    | '__root__'
    | '/'
    | '/extrato'
    | '/link'
    | '/onboarding'
    | '/parceiro'
    | '/receber'
    | '/sitemap.xml'
    | '/parceiro/depositos'
    | '/parceiro/pagamentos'
    | '/parceiro/promotores'
    | '/parceiro/'
    | '/parceiro/promotores/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtratoRoute: typeof ExtratoRoute
  LinkRoute: typeof LinkRoute
  OnboardingRoute: typeof OnboardingRoute
  ParceiroRoute: typeof ParceiroRouteWithChildren
  ReceberRoute: typeof ReceberRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receber': {
      id: '/receber'
      path: '/receber'
      fullPath: '/receber'
      preLoaderRoute: typeof ReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiro': {
      id: '/parceiro'
      path: '/parceiro'
      fullPath: '/parceiro'
      preLoaderRoute: typeof ParceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link': {
      id: '/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrato': {
      id: '/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof ExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiro/': {
      id: '/parceiro/'
      path: '/'
      fullPath: '/parceiro/'
      preLoaderRoute: typeof ParceiroIndexRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/promotores': {
      id: '/parceiro/promotores'
      path: '/promotores'
      fullPath: '/parceiro/promotores'
      preLoaderRoute: typeof ParceiroPromotoresRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/pagamentos': {
      id: '/parceiro/pagamentos'
      path: '/pagamentos'
      fullPath: '/parceiro/pagamentos'
      preLoaderRoute: typeof ParceiroPagamentosRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/depositos': {
      id: '/parceiro/depositos'
      path: '/depositos'
      fullPath: '/parceiro/depositos'
      preLoaderRoute: typeof ParceiroDepositosRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/promotores/$id': {
      id: '/parceiro/promotores/$id'
      path: '/$id'
      fullPath: '/parceiro/promotores/$id'
      preLoaderRoute: typeof ParceiroPromotoresIdRouteImport
      parentRoute: typeof ParceiroPromotoresRoute
    }
  }
}

interface ParceiroPromotoresRouteChildren {
  ParceiroPromotoresIdRoute: typeof ParceiroPromotoresIdRoute
}

const ParceiroPromotoresRouteChildren: ParceiroPromotoresRouteChildren = {
  ParceiroPromotoresIdRoute: ParceiroPromotoresIdRoute,
}

const ParceiroPromotoresRouteWithChildren =
  ParceiroPromotoresRoute._addFileChildren(ParceiroPromotoresRouteChildren)

interface ParceiroRouteChildren {
  ParceiroDepositosRoute: typeof ParceiroDepositosRoute
  ParceiroPagamentosRoute: typeof ParceiroPagamentosRoute
  ParceiroPromotoresRoute: typeof ParceiroPromotoresRouteWithChildren
  ParceiroIndexRoute: typeof ParceiroIndexRoute
}

const ParceiroRouteChildren: ParceiroRouteChildren = {
  ParceiroDepositosRoute: ParceiroDepositosRoute,
  ParceiroPagamentosRoute: ParceiroPagamentosRoute,
  ParceiroPromotoresRoute: ParceiroPromotoresRouteWithChildren,
  ParceiroIndexRoute: ParceiroIndexRoute,
}

const ParceiroRouteWithChildren = ParceiroRoute._addFileChildren(
  ParceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtratoRoute: ExtratoRoute,
  LinkRoute: LinkRoute,
  OnboardingRoute: OnboardingRoute,
  ParceiroRoute: ParceiroRouteWithChildren,
  ReceberRoute: ReceberRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
