/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ParceiroRouteImport } from './routes/parceiro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LinkRouteImport } from './routes/link'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ParceiroIndexRouteImport } from './routes/parceiro.index'
import { Route as ParceiroPromotoresRouteImport } from './routes/parceiro.promotores'
import { Route as ParceiroPagamentosRouteImport } from './routes/parceiro.pagamentos'
import { Route as ParceiroDepositosRouteImport } from './routes/parceiro.depositos'
import { Route as ParceiroPromotoresIndexRouteImport } from './routes/parceiro.promotores.index'
import { Route as ParceiroPromotoresIdRouteImport } from './routes/parceiro.promotores.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceiroRoute = ParceiroRouteImport.update({
  id: '/parceiro',
  path: '/parceiro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkRoute = LinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceiroIndexRoute = ParceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroPromotoresRoute = ParceiroPromotoresRouteImport.update({
  id: '/promotores',
  path: '/promotores',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroPagamentosRoute = ParceiroPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroDepositosRoute = ParceiroDepositosRouteImport.update({
  id: '/depositos',
  path: '/depositos',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroPromotoresIndexRoute = ParceiroPromotoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParceiroPromotoresRoute,
} as any)
const ParceiroPromotoresIdRoute = ParceiroPromotoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ParceiroPromotoresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRoute
  '/auth': typeof AuthRoute
  '/link': typeof LinkRoute
  '/onboarding': typeof OnboardingRoute
  '/parceiro': typeof ParceiroRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parceiro/depositos': typeof ParceiroDepositosRoute
  '/parceiro/pagamentos': typeof ParceiroPagamentosRoute
  '/parceiro/promotores': typeof ParceiroPromotoresRouteWithChildren
  '/parceiro/': typeof ParceiroIndexRoute
  '/parceiro/promotores/$id': typeof ParceiroPromotoresIdRoute
  '/parceiro/promotores/': typeof ParceiroPromotoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRoute
  '/auth': typeof AuthRoute
  '/link': typeof LinkRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parceiro/depositos': typeof ParceiroDepositosRoute
  '/parceiro/pagamentos': typeof ParceiroPagamentosRoute
  '/parceiro': typeof ParceiroIndexRoute
  '/parceiro/promotores/$id': typeof ParceiroPromotoresIdRoute
  '/parceiro/promotores': typeof ParceiroPromotoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRoute
  '/auth': typeof AuthRoute
  '/link': typeof LinkRoute
  '/onboarding': typeof OnboardingRoute
  '/parceiro': typeof ParceiroRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parceiro/depositos': typeof ParceiroDepositosRoute
  '/parceiro/pagamentos': typeof ParceiroPagamentosRoute
  '/parceiro/promotores': typeof ParceiroPromotoresRouteWithChildren
  '/parceiro/': typeof ParceiroIndexRoute
  '/parceiro/promotores/$id': typeof ParceiroPromotoresIdRoute
  '/parceiro/promotores/': typeof ParceiroPromotoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/link'
    | '/onboarding'
    | '/parceiro'
    | '/sitemap.xml'
    | '/parceiro/depositos'
    | '/parceiro/pagamentos'
    | '/parceiro/promotores'
    | '/parceiro/'
    | '/parceiro/promotores/$id'
    | '/parceiro/promotores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/link'
    | '/onboarding'
    | '/sitemap.xml'
    | '/parceiro/depositos'
    | '/parceiro/pagamentos'
    | '/parceiro'
    | '/parceiro/promotores/$id'
    | '/parceiro/promotores'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/link'
    | '/onboarding'
    | '/parceiro'
    | '/sitemap.xml'
    | '/parceiro/depositos'
    | '/parceiro/pagamentos'
    | '/parceiro/promotores'
    | '/parceiro/'
    | '/parceiro/promotores/$id'
    | '/parceiro/promotores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRoute
  AuthRoute: typeof AuthRoute
  LinkRoute: typeof LinkRoute
  OnboardingRoute: typeof OnboardingRoute
  ParceiroRoute: typeof ParceiroRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiro': {
      id: '/parceiro'
      path: '/parceiro'
      fullPath: '/parceiro'
      preLoaderRoute: typeof ParceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link': {
      id: '/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiro/': {
      id: '/parceiro/'
      path: '/'
      fullPath: '/parceiro/'
      preLoaderRoute: typeof ParceiroIndexRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/promotores': {
      id: '/parceiro/promotores'
      path: '/promotores'
      fullPath: '/parceiro/promotores'
      preLoaderRoute: typeof ParceiroPromotoresRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/pagamentos': {
      id: '/parceiro/pagamentos'
      path: '/pagamentos'
      fullPath: '/parceiro/pagamentos'
      preLoaderRoute: typeof ParceiroPagamentosRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/depositos': {
      id: '/parceiro/depositos'
      path: '/depositos'
      fullPath: '/parceiro/depositos'
      preLoaderRoute: typeof ParceiroDepositosRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/promotores/': {
      id: '/parceiro/promotores/'
      path: '/'
      fullPath: '/parceiro/promotores/'
      preLoaderRoute: typeof ParceiroPromotoresIndexRouteImport
      parentRoute: typeof ParceiroPromotoresRoute
    }
    '/parceiro/promotores/$id': {
      id: '/parceiro/promotores/$id'
      path: '/$id'
      fullPath: '/parceiro/promotores/$id'
      preLoaderRoute: typeof ParceiroPromotoresIdRouteImport
      parentRoute: typeof ParceiroPromotoresRoute
    }
  }
}

interface ParceiroPromotoresRouteChildren {
  ParceiroPromotoresIdRoute: typeof ParceiroPromotoresIdRoute
  ParceiroPromotoresIndexRoute: typeof ParceiroPromotoresIndexRoute
}

const ParceiroPromotoresRouteChildren: ParceiroPromotoresRouteChildren = {
  ParceiroPromotoresIdRoute: ParceiroPromotoresIdRoute,
  ParceiroPromotoresIndexRoute: ParceiroPromotoresIndexRoute,
}

const ParceiroPromotoresRouteWithChildren =
  ParceiroPromotoresRoute._addFileChildren(ParceiroPromotoresRouteChildren)

interface ParceiroRouteChildren {
  ParceiroDepositosRoute: typeof ParceiroDepositosRoute
  ParceiroPagamentosRoute: typeof ParceiroPagamentosRoute
  ParceiroPromotoresRoute: typeof ParceiroPromotoresRouteWithChildren
  ParceiroIndexRoute: typeof ParceiroIndexRoute
}

const ParceiroRouteChildren: ParceiroRouteChildren = {
  ParceiroDepositosRoute: ParceiroDepositosRoute,
  ParceiroPagamentosRoute: ParceiroPagamentosRoute,
  ParceiroPromotoresRoute: ParceiroPromotoresRouteWithChildren,
  ParceiroIndexRoute: ParceiroIndexRoute,
}

const ParceiroRouteWithChildren = ParceiroRoute._addFileChildren(
  ParceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRoute,
  AuthRoute: AuthRoute,
  LinkRoute: LinkRoute,
  OnboardingRoute: OnboardingRoute,
  ParceiroRoute: ParceiroRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
